# Generated by Django 4.2.16 on 2024-11-25 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('track_id', models.CharField(max_length=255)),
                ('artist_names', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('peak_rank', models.IntegerField()),
                ('previous_rank', models.IntegerField()),
                ('weeks_on_chart', models.IntegerField()),
                ('streams', models.IntegerField()),
                ('album_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(related_name='genres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
